resources:
- name: project-repository
  type: git
  icon: github
  source:
    uri: https://github.com/talentedasian/case-tracker-cloud.git
    branch: main
- name: docker-image-registry
  type: registry-image
  icon: docker
  source:
    repository: asianvietnamese/case_tracker
    tag: backend-latest
    username: asianvietnamese
    password: ((docker-password))

jobs:
- name: build-and-push
  plan:
  - get: project-repository
    trigger: true
  - task: build-task-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: project-repository
      outputs:
      - name: image
      params:
        CONTEXT: project-repository
      run:
        path: build
  - put: docker-image-registry
    params:
      image: image/image.tar